definitions:
  api.auth:
    properties:
      password:
        description: |
          PassWord 密码
        example: zhangsan
        type: string
      username:
        description: |
          UserName 用户名
        example: zhangsan
        type: string
    required:
    - username
    - password
    type: object
host: localhost:8000
info:
  contact: {}
  description: 用户登录注册/认证示例 Golang语言编写 Gin框架
  license:
    name: MIT
    url: https://github.com/sun-wenming/gin-auth/master/LICENSE
  termsOfService: https://github.com/sun-wenming/gin-auth
  title: 用户登录注册/认证示例
paths:
  /api/v1/test:
    get:
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 测试认证
      tags:
      - test
  /auth/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 用户信息
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/api.auth'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 登录
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 用户信息
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/api.auth'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 注册新用户
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
